services:
  backend:
    build: .
    container_name: mvp-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app   # monta a pasta local no /app do container
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mvp-db:5432/mvp
      - FLASK_ENV=development

  db:
    image: postgres:15
    container_name: mvp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvp
    ports:
      - "5455:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
